language: node_js
node_js: 8
before_script:
- yarn lint
- yarn test
script:
- yarn build:pack
deploy:
  provider: s3
  access_key_id:
    secure: mWp4GGYIY1bfbk9YlkbdRPUXr9kNhXM0HXPfmTCbrdAKizr+uWEZvjMFeKpsloWidqJxN0Oa3IORt5n+8NgbcAuC86I3FlnUsx/dZfkUDneoYrr8bU4BOm3tptkdsP9OKXRUUbf56nKaW1JnRntftFJQhQClBeznIgG/kmxJZQCiAbPc3BkVzHjc5BVSGfamN+hmc51uxtgnd9bXi2fSnPoWIWPisNJCTaQPcAqIyCRed99Ss4lD9vpa8NZVKM/cMDm+prEyUbg3hicgWyScaEb2DzI2y282cLlpzq3uQ+JH/n6IqeKckl3nFyh+KqFLzUbVnl/iWNRde4rCuj/u0Y9qKpwvJt58Tc1wASCGtkYFHIqQCRxvrggNuyHrQZMPukf4PTAwS9dPu450oUQyarQ6k41E5kvi9n07M0rWoOyBiaTmbWkIneorTkrd3nXUNmuF4h9WkbSIDmLWUuhoxuUCdN4IWOFKkbSQj5xV6JPJu0jCh7rJC1m4rGkrhenOU3WvW9saQ91yI5bItueq0J2s72CAH1aJ8xQKMxnYQjeqvE/3iH2lvFUmrMW0oJAcHm+xawvQxwfnadEAe2krhP1Acx9FhsGycLg+JX5WlgkuSuoU+0yzRsQBBk4ZZfliUMEtZngz+OPqgZbNmnjXj/2QhqdbFs5vayWeIQmRflo=
  secret_access_key:
    secure: FmWTCS9cWsnuleV/WlsGe3aplR75NzyhvJ7ct+vE9LoFRo+liXaFSMv3sKKmr78Fl0pLTUOMJJsTJIgm4PAjLlh5cbHRd2zcVsG3fF4WvWhJzqX4QYYQftylrJ8VSSiJT8Tg6iLWZtzIOlMOchQqalhHotgSgabL5NebKoEwVTZS3oME1wmIlvZiOUMFSypVHvgjenx44RuJEWFpp9IkZdU/+PBweqIEQuRQ7rPLSryMpXXfbdS979JRExW41QPd1pkShz1UrkiaximVezRJ+HHHoP0/wlUKs2hpCqm9LT28kieA3QdLZX5i2b0p2LPZwb0PPI2AHMuoCapHKnnRlvXKm0B+REyIBZo/SzUFdXoD36e3IiClPyWAwzD3LMD6ylxSAlbPq9i4cY7o/pT/5Fvc0rXXZQ33rmzE4rfLF0D717nKF9DTpV3VsC89dhbwG21GzgLdDb/HX7v0WBSwtZAY/kvWpzkkgEvBNSIyDCXN421MD/IBZ4P0DVdzn2dnu3AWMjx43P9rp7XP41gTWd2nPXGYdwTRDJzQ2jqXX0jsPBqKY/KwWW8qazOymtJUXKLKcrpjCTKoqguQgzM+4jIytkg1r7tK/fwWg7fElMa++IefdBcn9WZnvxUsLUHX2Tw0revhoysxiUyO1eBkISTqz2WyH/h0ga21RIs0cvg=
  bucket: webcatalog-apps
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
after_deploy:
- yarn build:publish
env:
  secure: PSQ5cBGGdblgKsF9sG0+Aw2c8A5S6ocS9AfieTxtsi3ixWTdWVaM1YvfjOa2HtN/0Y+wK4xO35M8Ps8Wmdgm0kC9AEJ/FR1d40aAOOKJVwvqb6MBqnsqnuqmdd6vZqYe11nyql/iqTNjbbUQpg3ka4X05Yh0pbApqvkJw1yvWtafZLD2Hv/fuHBT+fH20IKRx9ip8HUKHBS3hBsuIUKOOKZz6z7ZcfDOUNimf8scsoYdP6FALfU9BwNlwVhHXqaQQlPruQyyNdEeupYQtIktARSmAKUNFUDAEQJHH76qn4NiyUxKdmDunT2UCa2AowSEd2F8bEhKyG53w2vQ9VzKHPjQrZnfem9fePRiWKAKXTCrdvtBFXUmmeMf3zgchSor3ZlY/RLAryAqjxSeNo5YDqIA85XaTA51dmj0T+8RqpFIHnrjmIgcksGdWRYCY6fc/TJRfs4FC2kQkqLIUzMvk/hjDoqihceSOPoTEOSwrkNp2ELDtWrEozTx6BBfC0/xQeJpReXuUabxaeXZ6IzQ5ZnIZhSNIKHGzqYNqIZSSR2DuUEkDl9q1DSQ8QaahVhDY/P/3IViUQWaxQFOyZyh6iI1lyf2Lbj4f6zPtomFtQyfSeWNYXEFjggXreIbLyQVJ9f/xHzSi+/LA/7TZIg2pBJQFiWHRsoROxPViB/Q37U=
