language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode9.2
    node_js: 8
  - os: linux
    node_js: 8
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
sudo: required
cache: yarn
addons:
  apt:
    packages:
    - libxkbfile-dev
    - snapd
before_install:
- openssl aes-256-cbc -K $encrypted_c83a7fbb1c43_key -iv $encrypted_c83a7fbb1c43_iv -in snapcraft_login.enc -out snapcraft_login -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install snapcraft --classic; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then snap run snapcraft login --with snapcraft_login; fi
before_script:
- yarn lint
script:
- yarn dist
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb
  start; sleep 3; fi
- yarn test
deploy:
  on:
    tags: true
  provider: script
  script: bash snapcraft_deploy.sh
  skip_cleanup: true
