language: node_js
node_js: 8
before_script:
- yarn lint
- yarn test
- yarn build:pack
deploy:
  provider: s3
  access_key_id:
    secure: mWp4GGYIY1bfbk9YlkbdRPUXr9kNhXM0HXPfmTCbrdAKizr+uWEZvjMFeKpsloWidqJxN0Oa3IORt5n+8NgbcAuC86I3FlnUsx/dZfkUDneoYrr8bU4BOm3tptkdsP9OKXRUUbf56nKaW1JnRntftFJQhQClBeznIgG/kmxJZQCiAbPc3BkVzHjc5BVSGfamN+hmc51uxtgnd9bXi2fSnPoWIWPisNJCTaQPcAqIyCRed99Ss4lD9vpa8NZVKM/cMDm+prEyUbg3hicgWyScaEb2DzI2y282cLlpzq3uQ+JH/n6IqeKckl3nFyh+KqFLzUbVnl/iWNRde4rCuj/u0Y9qKpwvJt58Tc1wASCGtkYFHIqQCRxvrggNuyHrQZMPukf4PTAwS9dPu450oUQyarQ6k41E5kvi9n07M0rWoOyBiaTmbWkIneorTkrd3nXUNmuF4h9WkbSIDmLWUuhoxuUCdN4IWOFKkbSQj5xV6JPJu0jCh7rJC1m4rGkrhenOU3WvW9saQ91yI5bItueq0J2s72CAH1aJ8xQKMxnYQjeqvE/3iH2lvFUmrMW0oJAcHm+xawvQxwfnadEAe2krhP1Acx9FhsGycLg+JX5WlgkuSuoU+0yzRsQBBk4ZZfliUMEtZngz+OPqgZbNmnjXj/2QhqdbFs5vayWeIQmRflo=
  secret_access_key:
    secure: FmWTCS9cWsnuleV/WlsGe3aplR75NzyhvJ7ct+vE9LoFRo+liXaFSMv3sKKmr78Fl0pLTUOMJJsTJIgm4PAjLlh5cbHRd2zcVsG3fF4WvWhJzqX4QYYQftylrJ8VSSiJT8Tg6iLWZtzIOlMOchQqalhHotgSgabL5NebKoEwVTZS3oME1wmIlvZiOUMFSypVHvgjenx44RuJEWFpp9IkZdU/+PBweqIEQuRQ7rPLSryMpXXfbdS979JRExW41QPd1pkShz1UrkiaximVezRJ+HHHoP0/wlUKs2hpCqm9LT28kieA3QdLZX5i2b0p2LPZwb0PPI2AHMuoCapHKnnRlvXKm0B+REyIBZo/SzUFdXoD36e3IiClPyWAwzD3LMD6ylxSAlbPq9i4cY7o/pT/5Fvc0rXXZQ33rmzE4rfLF0D717nKF9DTpV3VsC89dhbwG21GzgLdDb/HX7v0WBSwtZAY/kvWpzkkgEvBNSIyDCXN421MD/IBZ4P0DVdzn2dnu3AWMjx43P9rp7XP41gTWd2nPXGYdwTRDJzQ2jqXX0jsPBqKY/KwWW8qazOymtJUXKLKcrpjCTKoqguQgzM+4jIytkg1r7tK/fwWg7fElMa++IefdBcn9WZnvxUsLUHX2Tw0revhoysxiUyO1eBkISTqz2WyH/h0ga21RIs0cvg=
  bucket: webcatalog-apps
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- yarn build:publish
