language: node_js
node_js: 8
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
- pip3 install --user -r requirements.txt
before_script:
- yarn lint
- yarn test
script:
- yarn build:pack
deploy:
  provider: script
  script: script/upload-to-github.sh
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- yarn build:publish
env:
  secure: PSQ5cBGGdblgKsF9sG0+Aw2c8A5S6ocS9AfieTxtsi3ixWTdWVaM1YvfjOa2HtN/0Y+wK4xO35M8Ps8Wmdgm0kC9AEJ/FR1d40aAOOKJVwvqb6MBqnsqnuqmdd6vZqYe11nyql/iqTNjbbUQpg3ka4X05Yh0pbApqvkJw1yvWtafZLD2Hv/fuHBT+fH20IKRx9ip8HUKHBS3hBsuIUKOOKZz6z7ZcfDOUNimf8scsoYdP6FALfU9BwNlwVhHXqaQQlPruQyyNdEeupYQtIktARSmAKUNFUDAEQJHH76qn4NiyUxKdmDunT2UCa2AowSEd2F8bEhKyG53w2vQ9VzKHPjQrZnfem9fePRiWKAKXTCrdvtBFXUmmeMf3zgchSor3ZlY/RLAryAqjxSeNo5YDqIA85XaTA51dmj0T+8RqpFIHnrjmIgcksGdWRYCY6fc/TJRfs4FC2kQkqLIUzMvk/hjDoqihceSOPoTEOSwrkNp2ELDtWrEozTx6BBfC0/xQeJpReXuUabxaeXZ6IzQ5ZnIZhSNIKHGzqYNqIZSSR2DuUEkDl9q1DSQ8QaahVhDY/P/3IViUQWaxQFOyZyh6iI1lyf2Lbj4f6zPtomFtQyfSeWNYXEFjggXreIbLyQVJ9f/xHzSi+/LA/7TZIg2pBJQFiWHRsoROxPViB/Q37U=
  global:
    secure: w/Wpp417oBfzqKdNMJVc89S4gnt8TZRJ6+io/q0uj9sRYvq0yJrl9DqB3TOdV6h+M6gWTbIBJhyhcnMP1fHWz/pEhegqHZbCYROyPCviPxc0oXWVb0bF1Eg7YLc1+CuWiMnOpc3g6GvD44jYwXGsrkBI8uYqZWfr5yb98r2483sF8LR/Ga9imSAf7CE6YZ9PVX3vDmrmGj3H8c7USz8sFQfXQaKt7FNA0huu1ZLgvAzonWtT+wrQuWGAkDaCdBYPZckEsNGMkjsHbG+fdaxomPVVcxb4COoBns4RIjCPi/BesIEMbiqOwaLVcNHUyf4sf1K9w85e7NDRxL1DEVphGZF8rkLtof8j9U6hQPj7HkEx6PFiEPrqcXkB57t1KUnIXKFQLufSTU/ndamxmeM017/fVazc71oCmFYoDe9t1HAzP850AnN4r8IRxStqmyTq+eQ9DwZoayo96nVHiMOnpMy12UoU4oH+3C/mjelQLSZJGn3b0LM+unbAF/IYElnjL/9B3MNcgtZT0ZML+4iPIAVOrymUs0+XK4WLhM9OZ3M4I791n7ENQcLLAirC3NG+akgcvFDlJzEOSOpgK6VfRwFAVlTcq62GHZL+mq1kH03RFN/X8at2J15+bdPfOBVjkkWkdfdq/JEIWjQBrstVsRmDthguU8LdudRL3Td7sA8=
