language: node_js
node_js: 6
os: osx
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - brew update
  - brew install imagemagick
script:
  - node-gyp rebuild -C ./node_modules/sharp
  - yarn start
after_success:
  - yarn global add surge
  - surge --project ./www --domain backend.getwebcatalog.com
