language: node_js
node_js: 6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn start
after_success:
  - yarn global add surge
  - surge --project ./www --domain backend.getwebcatalog.com
