language: node_js
node_js: 6
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn start
after_success:
  - yarn global add surge
  - surge --project ./www --domain backend.webcatalog.com
