language: node_js
node_js: 8
os: linux
cache:
  directories:
  - node_modules
script:
- "./publish.sh"
env:
  secure: LTCSP2ZBoO9PoO6GxiSyeZ0WHVjA2kZjLZNi6buRiJ/qeNirfaGvYgTNBCQMvu9o8DDTlSYHmEtez+813FLaxiaEjZK2QmORWTbjm9wS6gkUdi5Ci9y5JgaSfmJ0mYgfDumcjLme3G4XlNQFDX2FPrsB2VsGmtiAlBzMuS+QChPfYDvCcyAhlJik6Oai+sZiE4WT4Xy6g4kWCF4xT+dvULGzsByKiubYFE6hS6Uhvhs6DjD00T0uKQ67NP58DLJudcHX7Glb1CJ8SFQy5JNwzdHRCEioM1EGAZ8bGiTL2c06g8Xf0PBq6zR94TJ9aOM1afwJtW8IrokidWQEUtwF8Psa7qavci6ma/sqj+AhmK4j9kxMtD6eQZPr+N1C7Fut+HC6d1z7wqrWRSYfpyHfc3yJXby6N0Cnzmn8PGDMAJ4ydxhN2NYk/rC3NkXIRGnIj/zGfL2WPcxD8hsqSuQa9stTq+ciVRhnvYJ2VtT2xsZ0BI0J/qYiE1pH5Dp1c28O4TOL2Ncghql3AcqLqb+nNNtHPULOHWYiQU7HYKeJ4uCvF2VysoI1cOYyMMFDkmQeh9oC2aR5vw/vdg+AtaEe/B209ibjN/cv2IkT8ZrddAiNV8nRvHT5GpZDx7opDDsjA8iH8nVtVQorrXyU/+gjPuK56n5ORLEQG3SfdibBB2Y=
